-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: '4b49283'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0  # Use the ref you want to point at
    hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: flake8
    - id: detect-private-key
    # -   id: ...
